### ISSUE TITLE
ATL

### ISSUE THREAD

**Issue by mndhkr** [zodiacon/Win10SysProgBookSamples#9]
Chapter 02 - BasicSharing

Error on every atl function.
(ATL and MFC installed for current build tools)

`
Build started...
1>------ Build started: Project: BasicSharing, Configuration: Debug x64 ------
1>C:\Users\User\source\repos\Win10SysProgBookSamples-master\Chapter02\BasicSharing\BasicSharing.vcxproj(232,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\packages\wtl.10.0.9163\build\native\wtl.targets.
1>Done building project "BasicSharing.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

Obviusly I tried NuGet Package Restore with no success..
And I can't find relevant info on the net...

May you help me please? :)

**Comment by zodiacon** [comment]
Just so that others see it: Package restore should work. If not, add a reference to the WTL Nuget package.

**Comment by nrrpinto** [comment]
Restore did not work for me. Adding the reference also not.

What I did was, for each project, to open both files packages.config and .vcxproj and remove all references to the outdated packages. This should be done outside Visual Studio, for example in Code.
Then start the solution again in Visual Studio and install the packages again.

**Comment by zodiacon** [comment]
Thanks for the update!
